### ISSUE TITLE
Error in ContainerInitializer.php

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dependency-container#9]
I updated my MetaModels installation via composer, since I've done the update, I get the following error:

```
Warning: array_merge(): Argument #2 is not an array in composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php on line 289

#0 [internal function]: __error(2, 'array_merge(): ...', '/Applications/M...', 289, Array)
#1 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(289): array_merge(Array, NULL)
#2 composer/vendor/contao-community-alliance/dependency-container/src/DependencyInjection/Container/ContainerInitializer.php(333): DependencyInjection\Container\ContainerInitializer->provideSingletons(Object(Pimple))
#3 system/initialize.php(233): DependencyInjection\Container\ContainerInitializer->init()
#4 contao/main.php(24): require_once('/Applications/M...')
#5 {main}

```

I had a look on the requested line and it seems that the $GLOBALS['TL_HOOKS']['getPageLayout'] does not exist at every time. I think we need a condition to check if there is an array or not.

**Comment by bytehead** [comment]
same here...

**Comment by cboelter** [comment]
My quickfix solution is the following:

```
 if(is_array($GLOBALS['TL_HOOKS']['getPageLayout'])) {
                $container['page-provider'] = new PageProvider();

                $GLOBALS['TL_HOOKS']['getPageLayout'] = array_merge(
                    array(array('DependencyInjection\Container\PageProvider', 'setPage')),
                    $GLOBALS['TL_HOOKS']['getPageLayout']
                );
            }
```

**Comment by bytehead** [comment]
Thanks. I switched back to v1.6.1 (temporary).

**Comment by bibib** [comment]
Ich fürchte, ich habe diesen quickfix nicht richtig eingefügt. Fehler besteht weiterhin. Der betreffende Teil im Code sieht so aus:
```
    /**
     * Add the Contao singletons to the DIC.
     *
     * @param \Pimple $container The DIC to populate.
     *
     * @return void
     *
     * @SuppressWarnings(PHPMD.Superglobals)
     */
    protected function provideSingletons(\Pimple $container)
    {
        if (!isset($container['config'])) {
            $container['config'] = $container->share($this->getConfigProvider());
        }

        if (!isset($container['environment'])) {
            $container['environment'] = $container->share($this->getEnvironmentProvider());
        }

        if (!isset($container['database.connection'])) {
            $container['database.connection'] = $container->share($this->getDatabaseProvider());
        }

        if (!isset($container['input'])) {
            $container['input'] = $container->share($this->getInputProvider());
        }

        if (!isset($container['user'])) {
            $container['user'] = $container->share($this->getUserProvider());
        }

        if (!isset($container['session'])) {
            $container['session'] = $container->share($this->getSessionProvider());
        }

        if (!isset($container['page-provider'])) {
            $container['page-provider'] = new PageProvider();

            $GLOBALS['TL_HOOKS']['getPageLayout'] = array_merge(
                array(array('DependencyInjection\Container\PageProvider', 'setPage')),
                $GLOBALS['TL_HOOKS']['getPageLayout']
            );
        }

	 if(is_array($GLOBALS['TL_HOOKS']['getPageLayout'])) {
                $container['page-provider'] = new PageProvider();

                $GLOBALS['TL_HOOKS']['getPageLayout'] = array_merge(
                    array(array('DependencyInjection\Container\PageProvider', 'setPage')),
                    $GLOBALS['TL_HOOKS']['getPageLayout']
                );
            }
    }
```
Ist das korrekt?

**Comment by cboelter** [comment]
nope leider nicht korrekt, du musst das hier ... 

```
 $container['page-provider'] = new PageProvider();

            $GLOBALS['TL_HOOKS']['getPageLayout'] = array_merge(
                array(array('DependencyInjection\Container\PageProvider', 'setPage')),
                $GLOBALS['TL_HOOKS']['getPageLayout']
            );
```

Entfernen und durch den Code von mir erstzen.

**Comment by bibib** [comment]
Das hat geklappt, danke!

**Comment by discordier** [comment]
Has been fixed in 842a8e0726f38b53e08fe977603843f9b05e1bbf

**Comment by discordier** [comment]
Released as https://github.com/contao-community-alliance/dependency-container/releases/tag/1.7.1
